[package]
name = "tree-squatter-rust"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[features]
typed-query-scan = []
typed-presence-scan = []

[dependencies]
tree-sitter.workspace = true
regex.workspace = true

[build-dependencies]
cc.workspace = true

[dev-dependencies]
tree-squatter = { path = "../squatter" }
tree-sitter-json = "0.24"
tree-sitter-c = "=0.24.2"
tree-sitter-c-sharp = "0.23.5"
